name: 'OPG Repository Scanner'
description: 'This action scans the repository for manifest & lock files and generates a series of reports for visibility'
author: ''
inputs:
  repository_name:
    description: 'Repository name with owner, used for reporting only. For example, ministryofjustice/opg-repository-scanner'
    default: ${{ github.repository }}
  source_directory:
    required: false
    description: 'Directory to use as the base for scanning.'
    default: './'
  source_follow_symlinks:
    required: false
    description: 'Instruction to filesystem handling to follow symlinks or not.'
    default: false
  source_exclude:
    required: false
    description: 'List of folders / filepaths to exclude from all filesystem operations. This is parsed using JSON.parse to convert from a string.'
    default: '["(__samples__/*)", "(__tests__/*)", "(node_modules/*)","(vendor/*)"]'
  artifact_name:
    required: false
    description: 'The finished set of artifacts will be uploaded to this workflow under this name'
    default: 'repository-scan-result'


runs:
  using: 'node12'
  main: 'dist/index.js'
