name: 'OPG Repository Scanner'
description: ''
author: ''
inputs:
  configuration_file:
    required: false
    description: 'Provide an alternative configuration file from the included version'
runs:
  using: 'node12'
  main: 'dist/index.js'
