filesystem:
  directory: './'
  follow_symlinks: false

manifests:
  - name: composer
    uses: ComposerParser
  - name: package
    uses: PackageParser
output:
  - location: 'scan-result'
    as: 'json'
