source:
  directory: './'
  follow_symlinks: false
  exclude:
    - node_modules**/*
    - __samples__**/*
manifests:
  - name: composer
    uses: ComposerParser
  - name: package
    uses: PackageParser
artifact:
  name: 'repository-scan-result'
  as:
    - 'json'
