filesystem:
  directory: './'
  follow_symlinks: true

manifests_and_locks:
  - name: composer
    manifest:
      file: '**/composer.json'
      parser: ComposerManifest
      selectors:
        - '.require'
        - '.require-dev'
    lock:
      file: '**/composer.lock'
      parser: ComposerLock
      selectors:
        - '.packages'
        - '.packages-dev'
  - name: package
    manifest:
      file: '**/package.json'
      parser: ComposerManifest
      selectors:
        - '.dependencies'
        - '.devDependencies'
    lock:
      file: '**/package.lock'
      parser: ComposerLock
      selectors:
        - '.dependencies'
