follow_symlinks: true
manifests_and_locks:
  - name: composer
    manifest:
      file: '**/composer.json'
      type: key-value
      selectors:
        - '.require'
        - '.require-dev'
    lock:
      file: '**/composer.lock'
      type: key-value
      selectors:
        - '.packages'
        - '.packages-dev'
  - name: package
    manifest:
      file: '**/package.json'
      type: key-value
      selectors:
        - '.dependencies'
        - '.devDependencies'
    lock:
      file: '**/package.lock'
      type: key-value
      selectors:
        - '.dependencies'
