---
name: "[Typescript] Build and Tag from master"

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - 'dist/**'

jobs:
  build_and_tag:
    runs-on: "ubuntu-latest"
    steps:
      - name: Get date based timestamp for tagging
        id: datelabel
        run: echo "::set-output name=label::$(date +'%Y-%m-%d-%H%M%S')"
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: 'master'
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
      - name: "Run build process"
        run: |
          rm -Rf ./dist/
          npm install
          npm run all
      - name: "Commit the build files"
        run: |
          git config --global user.email "tools@digital.justice.gov.uk"
          git config --global user.name "Github Action"
          echo "${GITHUB_SHA}" > ./dist/sha.txt
          git add ./dist/ --force
          git commit -m "Build files for release"
          git tag -fa "typescript-${{ steps.datelabel.outputs.label }}" -m "typescript latest"
          git push origin master --force
          git push origin typescript-${{ steps.datelabel.outputs.label }} --force
      - name: Increment and push tag
        uses: anothrNick/github-tag-action@1.33.0
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
          RELEASE_BRANCHES: master
          WITH_V: false
          CUSTOM_TAG: "typescript-latest"
