---
name: "Build and Tag"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'dist/**'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"

      - name: "Run build process"
        run: |
          rm -Rf ./dist/
          npm install
          npm run all
      - name: "Commit the build files"
        run: |
          git config --global user.email "tools@digital.justice.gov.uk"
          git config --global user.name "Github Action"
          git add ./dist/ --force
          git commit -m "Build files for release"
          git push origin main --force
      - name: Increment and push tag
        uses: anothrNick/github-tag-action@1.33.0
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.1.0
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          WITH_V: true
