---
name: "pre-release"

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "*"

jobs:
  pre_release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - run: "npm install"
      - run: "npm run all"
      - uses: "marvinpinto/action-automatic-releases@v1.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./dist/index.js
            ./dist/index.js.map
            ./dist/sourcemap-register.js
            ./dist/licenses.txt
        id: "pre_release"
