manifests_and_locks:
  - name: composer
    manifest:
      file: '**/composer.json'
      type: foobar
      selectors:
        - '.require'
        - '.require-dev'
    lock:
      file: '**/composer.lock'
      type: key-value
      selectors:
        - '.packages'
        - '.packages-dev'
