manifests_and_locks:
  - name: composer
    manifest:
      file: '**/composer.json'
      parser: foobar
      selectors:
        - '.require'
        - '.require-dev'
    lock:
      file: '**/composer.lock'
      parser: json-key-value
      selectors:
        - '.packages'
        - '.packages-dev'
